config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"

  get "users/new"
  get "pages/home"
  get "pages/contact"
  get "pages/about"
	resources :users
	resources :sessions, :only => [:new, :create, :destroy]

	root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/home', :to => 'pages#home'
	match '/signup', :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'

  

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessor :password  
	attr_accessible :email, :name, :password, :password_confirmation
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, :presence => true,
									 :length => { :within => 1..50 }
	validates :email, :presence => true,
  									:format => { :with => email_regex },
										:uniqueness => { :case_sensitive => false }
	validates	:password, :presence	=> true,
											 :confirmation => true,
											 :length => { :within => 6..40 }
	before_save :encrypt_password

	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	def self.authenticate_with_salt(id, cookie_salt)
		user = find_by_id(id)
		(user && user.salt == cookie_salt) ? user : nil
	end

	private
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(password)
		end
		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	include SessionsHelper

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
		@title = "Sign in"
  end
	def create
		user = User.authenticate(params[:session][:email],
															params[:session][:password])
		if user.nil?
			flash.now[:error] = "Invalid email/password combination."
			@title = "Sign in"
			render 'new'
		else
			sign_in user
			redirect_to user
		end
	end
	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
		@user = User.new
		@title = "Sign up"
  end
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])	
		@title = @user.name
	end
	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		else
			@title = "Sign up"
			render 'new'
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title 
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
	def logo
		image_tag("logo.png", :alt => "Sample App", :class => "round")
	end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		current_user = user
	end
	def current_user=(user)
		@current_user = user
	end
	def current_user
		@current_user ||= user_from_remember_token
	end
	def signed_in?
		!current_user.nil?
	end
	def sign_out
		cookies.delete(:remember_token)
		current_user = nil
	end
	private
		def user_from_remember_token
			User.authenticate_with_salt(*remember_token)
		end
		def remember_token
			cookies.signed[:remember_token] || [nil, nil]
		end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.name,
																						:class => 'gravatar',
																						:gravatar => options)
	end
end

app/views/layouts/_header.html.erb
<header>
<%= link_to logo, root_path %>
<nav class="round">
<ul>
<li><%= link_to "Home", root_path %></li>
<% if signed_in? %>
<li><%= link_to "Profile", current_user %></li>
<% end %>
<li><%= link_to "Help", help_path %></li>
<% if signed_in? %>
<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
<% else %>
<li><%= link_to "Sign in", signin_path %></li>
<% end %>
</ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
			<%= yield %>
			</section>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<p>
	About us page
</p>

app/views/pages/contact.html.erb
<h1>Contact page</h1>
<p>
	Contact us page
</p>

app/views/pages/home.html.erb
<h1>Home page</h1>
<p>
	This is the content to be published on Home Page
</p>
<%= link_to "Sign up now!", '#', :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@user.errors.count, "error") %>
		prohibited this user from being saved:</h2>
		<p>There were problems with the following fields:</p>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/index.html.erb
<h1> Listing all the users </h1>
<table>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td><%= user.name %></td>
		<td><%= user.email %></td>
		<td><%= link_to 'Show', user %></td>
		<td><%= link_to 'Edit', edit_user_path(user) %></td>
		<td><%= link_to 'Destroy', user, :confirm => 'Are you sure?',:method => :delete %></td>
	</tr>
	<% end %>
</table>
<br />
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</td>
		<td class="sidebar round">
			<strong>Name</strong> <%= @user.name %><br />
			<strong>URL</strong> <%= link_to user_path(@user), @user %>
		</td>
	</tr>
</table>